name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  phpunit:
    name: Run tests on ${{ matrix.php-version }} with Symfony ${{ matrix.symfony }} and ${{ matrix.dependency-versions }} dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
        symfony:
          - '3.*'
          - '4.*'
          - '5.*'
          - '6.*'
          - '7.*'
        dependency-versions:
          - 'lowest'
          - 'highest'
        exclude:
          - { php-version: '7.1', symfony: '3.*', dependency-versions: 'lowest' }
          - { php-version: '7.2', symfony: '3.*' }
          - { php-version: '7.3', symfony: '3.*' }
          - { php-version: '7.4', symfony: '3.*' }
          - { php-version: '8.0', symfony: '3.*' }
          - { php-version: '8.1', symfony: '3.*' }
          - { php-version: '8.2', symfony: '3.*' }
          - { php-version: '8.3', symfony: '3.*' }
          - { php-version: '8.4', symfony: '3.*' }
          - { php-version: '7.1', symfony: '4.*', dependency-versions: 'lowest' }
          - { php-version: '7.2', symfony: '4.*' }
          - { php-version: '7.3', symfony: '4.*' }
          - { php-version: '7.4', symfony: '4.*' }
          - { php-version: '8.0', symfony: '4.*' }
          - { php-version: '8.1', symfony: '4.*' }
          - { php-version: '8.2', symfony: '4.*' }
          - { php-version: '8.3', symfony: '4.*' }
          - { php-version: '8.4', symfony: '4.*' }
          - { php-version: '7.1', symfony: '5.*' }
          - { php-version: '7.1', symfony: '6.*' }
          - { php-version: '7.2', symfony: '6.*' }
          - { php-version: '7.3', symfony: '6.*' }
          - { php-version: '7.4', symfony: '6.*' }
          - { php-version: '8.0', symfony: '6.*' }
          - { php-version: '7.1', symfony: '7.*' }
          - { php-version: '7.2', symfony: '7.*' }
          - { php-version: '7.3', symfony: '7.*' }
          - { php-version: '7.4', symfony: '7.*' }
          - { php-version: '8.0', symfony: '7.*' }
          - { php-version: '8.1', symfony: '7.*' }
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: flex

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        with:
          dependency-versions: ${{ matrix.dependency-versions }}

      - name: Run tests
        run: ./bin/phpunit
